// frontend/src/utils/countries.js
// Comprehensive list of countries for checkout and shipping address selection

export const COUNTRIES = [
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'Bangladesh',
  'India',
  'Pakistan',
  'United Arab Emirates',
  'Saudi Arabia',
  'Germany',
  'France',
  'Italy',
  'Spain',
  'Netherlands',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Belgium',
  'Austria',
  'Ireland',
  'Poland',
  'Portugal',
  'Greece',
  'Turkey',
  'Japan',
  'South Korea',
  'China',
  'Singapore',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Thailand',
  'Vietnam',
  'Qatar',
  'Kuwait',
  'Oman',
  'Bahrain',
  'Egypt',
  'Morocco',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Brazil',
  'Mexico',
  'Argentina',
  'Colombia',
  'Chile',
  'Peru',
  'New Zealand',
];

export default COUNTRIES;
